server:
  ssl:
    key-store: classpath:certificado.p12
    key-store-password: FULLRED
    key-alias: FULLRED
    key-password: FULLRED
    key-store-type: pkcs12
    port: ${PORT:8080}
spring:
  application:
    name: ms.sysredcolombia-rest
  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 600000
      idle-timeout: 60000
      max-lifetime: 1800000
      maximum-pool-size: 500
      minimum-idle: 20
      validation-timeout: 3000
    password: C4m1l02020+-+
    url: jdbc:mysql://sysredcartagena.duckdns.org/sysredpruebas?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: camiloleal
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true